// CodeGear C++Builder
// Copyright (c) 1995, 2012 by Embarcadero Technologies, Inc.
// All rights reserved

// (DO NOT EDIT: machine generated header) 'GLScene_RunTime.pas' rev: 24.00 (Win32)

#ifndef Glscene_runtimeHPP
#define Glscene_runtimeHPP

#pragma delphiheader begin
#pragma option push
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member 
#pragma pack(push,8)
#include <System.hpp>	// Pascal unit
#include <SysInit.hpp>	// Pascal unit
#include <GLScene.hpp>	// Pascal unit
#include <GLStrings.hpp>	// Pascal unit
#include <GLTexture.hpp>	// Pascal unit
#include <GLScreen.hpp>	// Pascal unit
#include <VectorGeometry.hpp>	// Pascal unit
#include <Info.hpp>	// Pascal unit
#include <PlugInManagerPropEditor.hpp>	// Pascal unit
#include <Utils3DS.hpp>	// Pascal unit
#include <File3DS.hpp>	// Pascal unit
#include <FileMD2.hpp>	// Pascal unit
#include <TypesMD2.hpp>	// Pascal unit
#include <Types3DS.hpp>	// Pascal unit
#include <Const3DS.hpp>	// Pascal unit
#include <AsyncTimer.hpp>	// Pascal unit
#include <FVectorEditor.hpp>	// Pascal unit
#include <FRTrackBarEdit.hpp>	// Pascal unit
#include <FRColorEditor.hpp>	// Pascal unit
#include <FRFaceEditor.hpp>	// Pascal unit
#include <FRMaterialPreview.hpp>	// Pascal unit
#include <FMaterialEditorForm.hpp>	// Pascal unit
#include <GLVectorFileObjects.hpp>	// Pascal unit
#include <FLibMaterialPicker.hpp>	// Pascal unit
#include <FRTextureEdit.hpp>	// Pascal unit
#include <Joystick.hpp>	// Pascal unit
#include <GLBehaviours.hpp>	// Pascal unit
#include <ScreenSaver.hpp>	// Pascal unit
#include <GLCadencer.hpp>	// Pascal unit
#include <XCollection.hpp>	// Pascal unit
#include <GLParticles.hpp>	// Pascal unit
#include <GLObjects.hpp>	// Pascal unit
#include <GLCollision.hpp>	// Pascal unit
#include <Spline.hpp>	// Pascal unit
#include <GLSoundFileObjects.hpp>	// Pascal unit
#include <GLSound.hpp>	// Pascal unit
#include <GLMesh.hpp>	// Pascal unit
#include <GLGraph.hpp>	// Pascal unit
#include <VectorLists.hpp>	// Pascal unit
#include <TypesSTL.hpp>	// Pascal unit
#include <GLFileSTL.hpp>	// Pascal unit
#include <GLExtrusion.hpp>	// Pascal unit
#include <GLFireFX.hpp>	// Pascal unit
#include <GLPortal.hpp>	// Pascal unit
#include <GLGraphics.hpp>	// Pascal unit
#include <GLMultiPolygon.hpp>	// Pascal unit
#include <GLFileOBJ.hpp>	// Pascal unit
#include <GLNavigator.hpp>	// Pascal unit
#include <GLMovement.hpp>	// Pascal unit
#include <GLSkydome.hpp>	// Pascal unit
#include <GLHUDObjects.hpp>	// Pascal unit
#include <XOpenGL.hpp>	// Pascal unit
#include <GLBitmapFont.hpp>	// Pascal unit
#include <GLTerrainRenderer.hpp>	// Pascal unit
#include <GLAVIRecorder.hpp>	// Pascal unit
#include <GLSVfw.hpp>	// Pascal unit
#include <GLThorFX.hpp>	// Pascal unit
#include <PersistentClasses.hpp>	// Pascal unit
#include <VectorTypes.hpp>	// Pascal unit
#include <GeometryBB.hpp>	// Pascal unit
#include <GLContext.hpp>	// Pascal unit
#include <Polynomials.hpp>	// Pascal unit
#include <GLWin32Context.hpp>	// Pascal unit
#include <GLCrossPlatform.hpp>	// Pascal unit
#include <GLParticleFX.hpp>	// Pascal unit
#include <GLzBuffer.hpp>	// Pascal unit
#include <GLMirror.hpp>	// Pascal unit
#include <GLWin32Viewer.hpp>	// Pascal unit
#include <GLROAMPatch.hpp>	// Pascal unit
#include <HeightTileFile.hpp>	// Pascal unit
#include <GLSpaceText.hpp>	// Pascal unit
#include <GLTimeEventsMgr.hpp>	// Pascal unit
#include <Octree.hpp>	// Pascal unit
#include <GLExplosionFx.hpp>	// Pascal unit
#include <GLGui.hpp>	// Pascal unit
#include <GLWindowsFont.hpp>	// Pascal unit
#include <GLShadowPlane.hpp>	// Pascal unit
#include <TGA.hpp>	// Pascal unit
#include <GLLensFlare.hpp>	// Pascal unit
#include <GLProcTextures.hpp>	// Pascal unit
#include <MeshUtils.hpp>	// Pascal unit
#include <GLHeightTileFileHDS.hpp>	// Pascal unit
#include <Q3BSP.hpp>	// Pascal unit
#include <FileOCT.hpp>	// Pascal unit
#include <GLFileOCT.hpp>	// Pascal unit
#include <GLFileQ3BSP.hpp>	// Pascal unit
#include <GLBSP.hpp>	// Pascal unit
#include <GLFileMS3D.hpp>	// Pascal unit
#include <TypesMS3D.hpp>	// Pascal unit
#include <Q3MD3.hpp>	// Pascal unit
#include <GLFileMD3.hpp>	// Pascal unit
#include <FileMD3.hpp>	// Pascal unit
#include <GLWindows.hpp>	// Pascal unit
#include <GLFileNMF.hpp>	// Pascal unit
#include <FileNMF.hpp>	// Pascal unit
#include <GLFileSMD.hpp>	// Pascal unit
#include <GLFileMD2.hpp>	// Pascal unit
#include <GLFile3DS.hpp>	// Pascal unit
#include <GLFilePLY.hpp>	// Pascal unit
#include <GLFileTIN.hpp>	// Pascal unit
#include <GLFileGTS.hpp>	// Pascal unit
#include <GLTexCombineShader.hpp>	// Pascal unit
#include <GLTextureCombiners.hpp>	// Pascal unit
#include <GLShadowVolume.hpp>	// Pascal unit
#include <ApplicationFileIO.hpp>	// Pascal unit
#include <GLSilhouette.hpp>	// Pascal unit
#include <GLBaseMeshSilhouette.hpp>	// Pascal unit
#include <GLStarRecord.hpp>	// Pascal unit
#include <GLGeomObjects.hpp>	// Pascal unit
#include <GLPolyhedron.hpp>	// Pascal unit
#include <GLTeapot.hpp>	// Pascal unit
#include <GLFullScreenViewer.hpp>	// Pascal unit
#include <GLMultiMaterialShader.hpp>	// Pascal unit
#include <GLUserShader.hpp>	// Pascal unit
#include <CurvesAndSurfaces.hpp>	// Pascal unit
#include <GLParametricSurfaces.hpp>	// Pascal unit
#include <GLFileNurbs.hpp>	// Pascal unit
#include <VerletClasses.hpp>	// Pascal unit
#include <SpatialPartitioning.hpp>	// Pascal unit
#include <GLOutlineShader.hpp>	// Pascal unit
#include <GLVerletClothify.hpp>	// Pascal unit
#include <GLMultiProxy.hpp>	// Pascal unit
#include <GLSkyBox.hpp>	// Pascal unit
#include <GLTree.hpp>	// Pascal unit
#include <GLMeshCSG.hpp>	// Pascal unit
#include <GLVerletSkeletonColliders.hpp>	// Pascal unit
#include <GLHiddenLineShader.hpp>	// Pascal unit
#include <GLProxyObjects.hpp>	// Pascal unit
#include <GLState.hpp>	// Pascal unit
#include <GLUtils.hpp>	// Pascal unit
#include <GLTilePlane.hpp>	// Pascal unit
#include <GLMeshOptimizer.hpp>	// Pascal unit
#include <GLImposter.hpp>	// Pascal unit
#include <GLWaterPlane.hpp>	// Pascal unit
#include <GLPerlinPFX.hpp>	// Pascal unit
#include <PerlinNoise.hpp>	// Pascal unit
#include <GLTexLensFlare.hpp>	// Pascal unit
#include <GLVfsPAK.hpp>	// Pascal unit
#include <TypesMDC.hpp>	// Pascal unit
#include <GLFileMDC.hpp>	// Pascal unit
#include <GLCelShader.hpp>	// Pascal unit
#include <GLFPSMovement.hpp>	// Pascal unit
#include <GLBumpShader.hpp>	// Pascal unit
#include <GLAnimatedSprite.hpp>	// Pascal unit
#include <GLFeedback.hpp>	// Pascal unit
#include <DXTC.hpp>	// Pascal unit
#include <GLMaterialScript.hpp>	// Pascal unit
#include <GLDCEMisc.hpp>	// Pascal unit
#include <GLEllipseCollision.hpp>	// Pascal unit
#include <GLDCE.hpp>	// Pascal unit
#include <GLProjectedTextures.hpp>	// Pascal unit
#include <GLBlur.hpp>	// Pascal unit
#include <GLPerlinBase.hpp>	// Pascal unit
#include <GLPerlin.hpp>	// Pascal unit
#include <GLTrail.hpp>	// Pascal unit
#include <GLScriptBase.hpp>	// Pascal unit
#include <GLFileMD5.hpp>	// Pascal unit
#include <GLSpatialPartitioning.hpp>	// Pascal unit
#include <VRMLParser.hpp>	// Pascal unit
#include <GLFileVRML.hpp>	// Pascal unit
#include <LWObjects.hpp>	// Pascal unit
#include <GLFileLWO.hpp>	// Pascal unit
#include <PictureRegisteredFormats.hpp>	// Pascal unit
#include <GLLinePFX.hpp>	// Pascal unit
#include <GLGameMenu.hpp>	// Pascal unit
#include <GLTexturedHDS.hpp>	// Pascal unit
#include <GLHeightData.hpp>	// Pascal unit
#include <GLAsyncHDS.hpp>	// Pascal unit
#include <GLEParticleMasksManager.hpp>	// Pascal unit
#include <GLConsole.hpp>	// Pascal unit
#include <GLSmoothNavigator.hpp>	// Pascal unit
#include <GLSimpleNavigation.hpp>	// Pascal unit
#include <GLAtmosphere.hpp>	// Pascal unit
#include <GLMaterialMultiProxy.hpp>	// Pascal unit
#include <GLShaderCombiner.hpp>	// Pascal unit
#include <GLCustomShader.hpp>	// Pascal unit
#include <GLSLShader.hpp>	// Pascal unit
#include <GLSLDiffuseSpecularShader.hpp>	// Pascal unit
#include <GLSLBumpShader.hpp>	// Pascal unit
#include <GLAsmShader.hpp>	// Pascal unit
#include <GLPostEffects.hpp>	// Pascal unit
#include <GLShadowHDS.hpp>	// Pascal unit
#include <GLSLProjectedTextures.hpp>	// Pascal unit
#include <GLViewer.hpp>	// Pascal unit
#include <GLGizmo.hpp>	// Pascal unit
#include <GLFile3DSSceneObjects.hpp>	// Pascal unit
#include <GLTextureSharingShader.hpp>	// Pascal unit
#include <GLColor.hpp>	// Pascal unit
#include <BaseClasses.hpp>	// Pascal unit
#include <GLCoordinates.hpp>	// Pascal unit
#include <GLManager.hpp>	// Pascal unit
#include <GLNodes.hpp>	// Pascal unit
#include <GLRenderContextInfo.hpp>	// Pascal unit
#include <GLFileB3D.hpp>	// Pascal unit
#include <GLFileGL2.hpp>	// Pascal unit
#include <GLFileLMTS.hpp>	// Pascal unit
#include <TypesB3D.hpp>	// Pascal unit
#include <FileB3D.hpp>	// Pascal unit
#include <FileGL2.hpp>	// Pascal unit
#include <GLFileASE.hpp>	// Pascal unit
#include <GLGLUTesselation.hpp>	// Pascal unit
#include <GLMeshBuilder.hpp>	// Pascal unit
#include <GLMaterial.hpp>	// Pascal unit
#include <GLDynamicTexture.hpp>	// Pascal unit
#include <GLRagdoll.hpp>	// Pascal unit
#include <GLVerletClasses.hpp>	// Pascal unit
#include <BumpMapping.hpp>	// Pascal unit
#include <GeometryCoordinates.hpp>	// Pascal unit
#include <VerletHairClasses.hpp>	// Pascal unit
#include <GLObjectManager.hpp>	// Pascal unit
#include <GLCameraController.hpp>	// Pascal unit
#include <GLFBORenderer.hpp>	// Pascal unit
#include <GLKeyboard.hpp>	// Pascal unit
#include <GLTextureFormat.hpp>	// Pascal unit
#include <GLFileDDS.hpp>	// Pascal unit
#include <GLFileHDR.hpp>	// Pascal unit
#include <GLFileO3TC.hpp>	// Pascal unit
#include <DDSImage.hpp>	// Pascal unit
#include <HDRImage.hpp>	// Pascal unit
#include <O3TCImage.hpp>	// Pascal unit
#include <RGBE.hpp>	// Pascal unit
#include <GLCompositeImage.hpp>	// Pascal unit
#include <GLFBO.hpp>	// Pascal unit
#include <GLFileMP3.hpp>	// Pascal unit
#include <GLFileWAV.hpp>	// Pascal unit
#include <GLSMWaveOut.hpp>	// Pascal unit
#include <GLFileJPEG.hpp>	// Pascal unit
#include <GLFilePNG.hpp>	// Pascal unit
#include <GLSJPG.hpp>	// Pascal unit
#include <LIBPNG.hpp>	// Pascal unit
#include <GLSLanguage.hpp>	// Pascal unit
#include <OpenGLAdapter.hpp>	// Pascal unit
#include <GLMultisampleImage.hpp>	// Pascal unit
#include <GLSZLibEx.hpp>	// Pascal unit
#include <GLSZLibExApi.hpp>	// Pascal unit
#include <GLSArchiveManager.hpp>	// Pascal unit
#include <GLSCrossXML.hpp>	// Pascal unit
#include <OpenGLTokens.hpp>	// Pascal unit
#include <GLPipelineTransformation.hpp>	// Pascal unit
#include <GLSelection.hpp>	// Pascal unit
#include <ImageUtils.hpp>	// Pascal unit
#include <GLSGenerics.hpp>	// Pascal unit
#include <GLSLog.hpp>	// Pascal unit
#include <GLSLParameter.hpp>	// Pascal unit
#include <GLMaterialEx.hpp>	// Pascal unit
#include <FRUniformEditor.hpp>	// Pascal unit
#include <GLSMemo.hpp>	// Pascal unit
#include <GLSceneForm.hpp>	// Pascal unit
#include <GLFileBMP.hpp>	// Pascal unit
#include <GLFileTGA.hpp>	// Pascal unit
#include <GLScene.FMX.Viewer.hpp>	// Pascal unit
#include <OpenGL1x.hpp>	// Pascal unit
#include <GLBumpmapHDS.hpp>	// Pascal unit
#include <PlugInIntf.hpp>	// Pascal unit
#include <PlugInManager.hpp>	// Pascal unit
#include <GLTextureImageEditors.hpp>	// Pascal unit
#include <GuiSkinEditorFormUnit.hpp>	// Pascal unit
#include <GLPhongShader.hpp>	// Pascal unit
#include <GLCanvas.hpp>	// Pascal unit
#include <GLSLPostBlurShader.hpp>	// Pascal unit
#include <GLTypes.hpp>	// Pascal unit
#include <Winapi.Windows.hpp>	// Pascal unit
#include <System.Internal.ExcUtils.hpp>	// Pascal unit
#include <System.SysUtils.hpp>	// Pascal unit
#include <System.VarUtils.hpp>	// Pascal unit
#include <System.Variants.hpp>	// Pascal unit
#include <System.Math.hpp>	// Pascal unit
#include <System.TimeSpan.hpp>	// Pascal unit
#include <System.SyncObjs.hpp>	// Pascal unit
#include <System.Generics.Defaults.hpp>	// Pascal unit
#include <System.Rtti.hpp>	// Pascal unit
#include <System.TypInfo.hpp>	// Pascal unit
#include <System.Classes.hpp>	// Pascal unit
#include <System.DateUtils.hpp>	// Pascal unit
#include <System.IOUtils.hpp>	// Pascal unit
#include <System.Win.Registry.hpp>	// Pascal unit
#include <Vcl.Graphics.hpp>	// Pascal unit
#include <System.Actions.hpp>	// Pascal unit
#include <Vcl.ActnList.hpp>	// Pascal unit
#include <System.HelpIntfs.hpp>	// Pascal unit
#include <Winapi.UxTheme.hpp>	// Pascal unit
#include <Vcl.GraphUtil.hpp>	// Pascal unit
#include <Vcl.StdCtrls.hpp>	// Pascal unit
#include <Winapi.ShellAPI.hpp>	// Pascal unit
#include <Vcl.Printers.hpp>	// Pascal unit
#include <Vcl.Clipbrd.hpp>	// Pascal unit
#include <Vcl.ComCtrls.hpp>	// Pascal unit
#include <Vcl.Dialogs.hpp>	// Pascal unit
#include <Vcl.ExtCtrls.hpp>	// Pascal unit
#include <Vcl.Themes.hpp>	// Pascal unit
#include <Winapi.FlatSB.hpp>	// Pascal unit
#include <Vcl.Forms.hpp>	// Pascal unit
#include <Vcl.Menus.hpp>	// Pascal unit
#include <System.Win.ComObj.hpp>	// Pascal unit
#include <Vcl.Controls.hpp>	// Pascal unit
#include <Vcl.Imaging.pngimage.hpp>	// Pascal unit
#include <Vcl.Buttons.hpp>	// Pascal unit
#include <Vcl.ExtDlgs.hpp>	// Pascal unit
#include <Vcl.Imaging.jpeg.hpp>	// Pascal unit
#include <Xml.Win.msxmldom.hpp>	// Pascal unit
#include <Xml.Xmldom.hpp>	// Pascal unit
#include <Xml.XMLSchema.hpp>	// Pascal unit
#include <FMX.Materials.hpp>	// Pascal unit
#include <FMX.Filter.Custom.hpp>	// Pascal unit
#include <FMX.Filter.Standard.hpp>	// Pascal unit
#include <FMX.Effects.hpp>	// Pascal unit
#include <FMX.Objects.hpp>	// Pascal unit
#include <FMX.Import.hpp>	// Pascal unit
#include <FMX.Objects3D.hpp>	// Pascal unit
#include <FMX.Types3D.hpp>	// Pascal unit
#include <Winapi.GDIPOBJ.hpp>	// Pascal unit
#include <FMX.Canvas.GDIP.hpp>	// Pascal unit
#include <FMX.Printer.hpp>	// Pascal unit
#include <FMX.Ani.hpp>	// Pascal unit
#include <FMX.Layouts.hpp>	// Pascal unit
#include <FMX.Menus.hpp>	// Pascal unit
#include <FMX.Memo.hpp>	// Pascal unit
#include <FMX.ExtCtrls.hpp>	// Pascal unit
#include <FMX.Pickers.hpp>	// Pascal unit
#include <FMX.ListBox.hpp>	// Pascal unit
#include <FMX.Edit.hpp>	// Pascal unit
#include <FMX.Controls.hpp>	// Pascal unit
#include <FMX.Grid.hpp>	// Pascal unit
#include <FMX.Styles.hpp>	// Pascal unit
#include <FMX.Dialogs.hpp>	// Pascal unit
#include <FMX.Forms.hpp>	// Pascal unit
#include <Winapi.D2D1.hpp>	// Pascal unit
#include <FMX.Context.DX10.hpp>	// Pascal unit
#include <FMX.Canvas.D2D.hpp>	// Pascal unit
#include <FMX.Context.DX9.hpp>	// Pascal unit
#include <FMX.Gestures.hpp>	// Pascal unit
#include <FMX.Gestures.Win.hpp>	// Pascal unit
#include <FMX.Platform.Win.hpp>	// Pascal unit
#include <FMX.Platform.hpp>	// Pascal unit
#include <FMX.Types.hpp>	// Pascal unit

//-- user supplied -----------------------------------------------------------

namespace Glscene_runtime
{
//-- type declarations -------------------------------------------------------
//-- var, const, procedure ---------------------------------------------------
}	/* namespace Glscene_runtime */
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_GLSCENE_RUNTIME)
using namespace Glscene_runtime;
#endif
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// Glscene_runtimeHPP
