//AlitaOnHeightfield Landscape Demo By René Lindsay
//
// The actor was downloaded from www.polycount.com
// The heightfied and texture was generated by Terragen
//          (see http://www.terragen.de/index.htm)
//
// Sample Perf (default map, default size, etc.):
//     K6-400 + Voodoo3 (16bits)     =  13 FPS
//     K7-500 + GeForce SDR (32bits) = 150 FPS
//     Windows 10 (64bits): driver 361.75 from 27.01.2016
//     Intel(R)Core(TM)i3-3120M CPU@2.50GHz + GeForce GT 630M = 230 FPS

program AlitaOnHeightfield;

uses
  Forms,
  Main in 'Main.pas' {Form1};

{$R *.RES}

begin
  Application.Initialize;
  Application.CreateForm(TForm1, Form1);
  Application.Run;
end.
